package com.iconshift.core.miui

import java.io.ByteArrayOutputStream
import java.util.zip.ZipEntry
import java.util.zip.ZipOutputStream

/**
 * Builds a minimal MIUI/HyperOS theme package (`.mtz`) that carries only the `icons` component.
 * Layout: `description.xml` + `icons` (itself a zip, no extension).
 */
object MtzPackager {

    data class Description(
        val title: String = "IconShift",
        val designer: String = "IconShift",
        val author: String = "IconShift",
        val version: String = "1.0",
        /** Should match the device's `ro.miui.ui.version.code`; ThemeManager may reject a mismatch. */
        val uiVersion: String = "",
        val description: String = "Per-app icons generated by IconShift",
    )

    fun descriptionXml(d: Description): String = buildString {
        appendLine("""<?xml version="1.0" encoding="UTF-8"?>""")
        appendLine("<MIUI-Theme>")
        appendLine("    <title>${esc(d.title)}</title>")
        appendLine("    <designer>${esc(d.designer)}</designer>")
        appendLine("    <author>${esc(d.author)}</author>")
        appendLine("    <version>${esc(d.version)}</version>")
        if (d.uiVersion.isNotBlank()) appendLine("    <uiVersion>${esc(d.uiVersion)}</uiVersion>")
        appendLine("    <description>${esc(d.description)}</description>")
        appendLine("</MIUI-Theme>")
    }

    fun build(description: Description, iconsZip: ByteArray): ByteArray {
        val bos = ByteArrayOutputStream()
        ZipOutputStream(bos).use { zout ->
            zout.putNextEntry(ZipEntry("description.xml"))
            zout.write(descriptionXml(description).toByteArray(Charsets.UTF_8))
            zout.closeEntry()
            zout.putNextEntry(ZipEntry("icons"))
            zout.write(iconsZip)
            zout.closeEntry()
        }
        return bos.toByteArray()
    }

    private fun esc(s: String) = s
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace("\"", "&quot;")
}
